import os


DEFAULT_TEMP_CHANNEL_PREFIX = "Yap"
JOIN_TO_CREATE_NAME = "Join to Yap"
DEFAULT_NOTIFICATION_COOLDOWN_SECONDS = 45
NOTIFICATION_DELETE_AFTER_SECONDS = 15
RECONCILE_INTERVAL_MINUTES = 10

DATA_DIR = os.getenv("YAPHUB_DATA_DIR", "data")
DATABASE_PATH = os.getenv("YAPHUB_DB_PATH", os.path.join(DATA_DIR, "yaphub.sqlite3"))
